CC = gcc
CFLAGS = -std=c99 -Wall -g 

TestClientGUI: ./src/GTK.o ./src/GTKMain.c
	$(CC) $(CCFLAGS) ./src/GTK.o ./src/GTKMain.c -o ./bin/TestClientGUI

TestServerGUI:

TestRSA: 

TestServer:

TestClient:
